spring.application.name=management

spring.data.mongodb.uri=mongodb+srv://sandeshchavan_db_user:Sandesh2004@hospitalcluster.swntg1r.mongodb.net/hospitalDB?retryWrites=true&w=majority

spring.main.allow-circular-references=true